module.exports.descriptors=[
    'Cleaning',
    'Construction',
    'Stationery',
    'Fabrication',
    'Sports',
    'Aluminium',
    'Oil',
    'Transport',
    'Shipping',
    'Manpower',
    'Agriculture',
    'Chemical',
    'Interior Designing',
    'Accounting',
    'Refrigeration',
    'Industrial',
    'Sign',
    'Technical'
]

module.exports.categories=[
    'Electronics', 'Food and Beverages', 'Fashion', 'Mobiles', 'Grocery', 'Appliances', 'Books', 'Stationery And Office Supplies', 'Auto Accessories', 'Safety And Hygiene Essentials', 'Grooming', 'Sports And Fitness'
]

module.exports.places=[
    'Services',
    'Products',
    'Supplier',
    'Manufacturer',
    'Services',
    'Trader',
    'Equipment',
    'Rental',
    'Dealer',
    'Wholesaler',
    'Services',
    'Supplier',
]

module.exports.seedImages=[
    'https://res.cloudinary.com/dwh4llt0c/image/upload/v1666352127/SnapBuy/planetcare-5cpBWEl6y6c-unsplash_a55bxx.jpg',
    'https://res.cloudinary.com/dwh4llt0c/image/upload/v1666352126/SnapBuy/clayton-elliot-Dx2t4hutl6U-unsplash_ykc7xv.jpg',
    'https://res.cloudinary.com/dwh4llt0c/image/upload/v1666352125/SnapBuy/daniel-norris-ZN_86cZrSN0-unsplash_kttf2q.jpg',
    'https://res.cloudinary.com/dwh4llt0c/image/upload/v1666352123/SnapBuy/manik-roy-DITbY0qXoaE-unsplash_jhi5by.jpg',
    'https://res.cloudinary.com/dwh4llt0c/image/upload/v1666352538/SnapBuy/katherine-chase-VNBUJ6imfGs-unsplash_tgshhv.jpg',
    'https://res.cloudinary.com/dwh4llt0c/image/upload/v1666352540/SnapBuy/amir-2O3NECoCdKw-unsplash_bc9xbp.jpg',
    'https://res.cloudinary.com/dwh4llt0c/image/upload/v1666352750/SnapBuy/aram-sabah-jAPFrA9YJsQ-unsplash_txffdb.jpg',
    'https://res.cloudinary.com/dwh4llt0c/image/upload/v1666352751/SnapBuy/chris-taljaard-S__3xvlGDe8-unsplash_k0tqqc.jpg',
    'https://res.cloudinary.com/dwh4llt0c/image/upload/v1666352752/SnapBuy/davide-boscolo-gz9njd0zYbQ-unsplash_ytjcvo.jpg',
    'https://res.cloudinary.com/dwh4llt0c/image/upload/v1666352754/SnapBuy/blaz-erzetic-g5f0BJq-FRs-unsplash_rnlws0.jpg',
    'https://res.cloudinary.com/dwh4llt0c/image/upload/v1666352755/SnapBuy/paolo-giubilato-ZwKCWVFdrcs-unsplash_y6lg0p.jpg',
    'https://res.cloudinary.com/dwh4llt0c/image/upload/v1666352757/SnapBuy/trinity-nguyen-4KFaFOfdRWg-unsplash_uzltak.jpg',
    'https://res.cloudinary.com/dwh4llt0c/image/upload/v1666352926/SnapBuy/chris-briggs-FobzAZJGM9M-unsplash_wyzoa8.jpg',
    'https://res.cloudinary.com/dwh4llt0c/image/upload/v1666352928/SnapBuy/salman-hossain-saif-yVFd9eqZ71A-unsplash_ht4htg.jpg',
    'https://res.cloudinary.com/dwh4llt0c/image/upload/v1666352931/SnapBuy/kelly-sikkema-IZOAOjvwhaM-unsplash_h814xd.jpg',
    'https://res.cloudinary.com/dwh4llt0c/image/upload/v1666352934/SnapBuy/cristina-anne-costello-rank-Px49iI-unsplash_gkpcxm.jpg',
    'https://res.cloudinary.com/dwh4llt0c/image/upload/v1666353105/SnapBuy/trinh-minh-th-twN2viFvWd0-unsplash_bvp1dn.jpg',
    'https://res.cloudinary.com/dwh4llt0c/image/upload/v1666353106/SnapBuy/tanya-layko-QINaeQQHghQ-unsplash_hms9rh.jpg',
    'https://res.cloudinary.com/dwh4llt0c/image/upload/v1666353106/SnapBuy/hannah-morgan-ycVFts5Ma4s-unsplash_rog0ze.jpg',
    'https://res.cloudinary.com/dwh4llt0c/image/upload/v1666353107/SnapBuy/laura-chouette-W-7k72ThEr0-unsplash_ghz6fw.jpg',
    'https://res.cloudinary.com/dwh4llt0c/image/upload/v1666353107/SnapBuy/alexandra-gorn-WF0LSThlRmw-unsplash_nfcnsw.jpg',
    'https://res.cloudinary.com/dwh4llt0c/image/upload/v1666353333/SnapBuy/the-humble-co-cADflhZzgyo-unsplash_vqwbvj.jpg',
    'https://res.cloudinary.com/dwh4llt0c/image/upload/v1666353335/SnapBuy/maskmedicare-shop-Nq5XRCXYBNY-unsplash_xlnhql.jpg',
    'https://res.cloudinary.com/dwh4llt0c/image/upload/v1666353339/SnapBuy/tai-s-captures-0I52FCHNjoU-unsplash_whg3ks.jpg',
    'https://res.cloudinary.com/dwh4llt0c/image/upload/v1666353340/SnapBuy/kelly-sikkema-xp-ND7NjWaA-unsplash_dm7j4h.jpg',
    'https://res.cloudinary.com/dwh4llt0c/image/upload/v1666353514/SnapBuy/stylite-yu-aKjAbP8DrMw-unsplash_eic232.jpg',
    'https://res.cloudinary.com/dwh4llt0c/image/upload/v1666353515/SnapBuy/artboard-studio-c-KRSHct7Ho-unsplash_hykskz.jpg',
    'https://res.cloudinary.com/dwh4llt0c/image/upload/v1666353518/SnapBuy/savannah-wakefield-JuGit9k28xw-unsplash_fo66e1.jpg',
    'https://res.cloudinary.com/dwh4llt0c/image/upload/v1666353518/SnapBuy/dee-copper-and-wild-yf61jhXNmYo-unsplash_syibtd.jpg',
    'https://res.cloudinary.com/dwh4llt0c/image/upload/v1666353520/SnapBuy/kasturi-roy-mgAjrBPU0pc-unsplash_gcatjy.jpg',
    'https://res.cloudinary.com/dwh4llt0c/image/upload/v1666353520/SnapBuy/linh-nguyen-8RtITvP9Scw-unsplash_e7zs51.jpg',
    'https://res.cloudinary.com/dwh4llt0c/image/upload/v1666353521/SnapBuy/kasturi-roy-Ax_ET5_BdGI-unsplash_zzwhi7.jpg'

]